### ISSUE TITLE
Toolchain

### ISSUE THREAD

**Issue by ezera23** [halcyon441-png/android_samsung_exynos9610#4]
Hello, can you just send me your toolchain please as example....I will not ask any support just need hint to build it.

**Comment by fx-09** [comment]
Hello, @ezera23, thank you for check out my source, this is the Linaro link, you can download it right here:
[de_link](https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/aarch64-linux-gnu/gcc-linaro-7.2.1-2017.11-i686_aarch64-linux-gnu.tar.xz.asc)
If you encountered any more problem, please let me know right below.
-halcyon441

**Comment by halcyon441-png** [comment]
Also

**Comment by ezera23** [comment]
Appreciated, have a great day! Thanks
