### ISSUE TITLE
Build Quantum Quack 2.0

### ISSUE THREAD

**Issue by ezera23** [halcyon441-png/android_samsung_exynos9610#5]
Hello, i have an issue building Quantum Quack 2.0:

ld does not support --fix-cortex-a53-843419

Usually this come from path in CROSS_COMPILER. I use gcc linaro 2017 (link you provided to me)

I use clang from the toolchain provided in the source and gcc linaro from the link you provided me in the previous issue. All packages and dep have been installed and your instructions followed A to Z :)

Here is the output

> Building zImage for A507FN
GCC_TOOLCHAIN - /
'rivers/Kconfig:229:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:5:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:6:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:7:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:8:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:16:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:17:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:18:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:19:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:19:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:22:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:23:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:24:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:25:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:25:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:28:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:29:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:30:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:34:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:35:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:36:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:37:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:37:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:40:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:41:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:42:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:43:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:43:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:46:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:47:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:48:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:49:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:49:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:52:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:53:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:54:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:55:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:56:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:56:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:61:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:62:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:63:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:64:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:65:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:65:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:70:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:71:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:72:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:73:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:74:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:74:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:79:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:80:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:81:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:82:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:83:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:83:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:89:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:90:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:91:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:92:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:93:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:98:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:98:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:5:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:6:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:7:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:8:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:16:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:17:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:18:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:19:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:20:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:20:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:27:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:28:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:29:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:30:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:38:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:39:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:40:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:41:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:42:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:42:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:49:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:50:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:51:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:52:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:53:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:53:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:60:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:61:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:62:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:63:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:64:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:64:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:71:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:72:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:73:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:74:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:75:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:75:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:81:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:82:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:83:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:84:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:85:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:86:warning: ignoring unsupported character '
configuration written to .config
GCC_TOOLCHAIN - /
arch/arm64/Makefile:27: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum
arch/arm64/Makefile:57: Detected assembler with broken .inst; disassembly will be unreliable
GCC_TOOLCHAIN - /
scripts/kconfig/conf  --silentoldconfig Kconfig
'rivers/Kconfig:229:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:5:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:6:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:7:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:8:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:16:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:17:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:18:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:19:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:19:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:22:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:23:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:24:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:25:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:25:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:28:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:29:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:30:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:34:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:35:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:36:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:37:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:37:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:40:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:41:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:42:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:43:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:43:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:46:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:47:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:48:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:49:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:49:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:52:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:53:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:54:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:55:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:56:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:56:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:61:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:62:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:63:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:64:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:65:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:65:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:70:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:71:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:72:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:73:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:74:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:74:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:79:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:80:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:81:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:82:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:83:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:83:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:89:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:90:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:91:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:92:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:93:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:98:warning: ignoring unsupported character '
'rivers/sensorhub/Kconfig:98:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:5:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:6:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:7:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:8:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:9:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:16:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:17:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:18:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:19:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:20:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:20:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:27:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:28:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:29:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:30:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:31:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:38:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:39:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:40:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:41:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:42:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:42:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:49:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:50:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:51:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:52:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:53:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:53:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:60:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:61:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:62:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:63:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:64:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:64:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:71:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:72:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:73:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:74:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:75:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:75:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:81:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:82:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:83:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:84:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:85:warning: ignoring unsupported character '
'rivers/sensorhub/factory/Kconfig:86:warning: ignoring unsupported character '
GCC_TOOLCHAIN - /
arch/arm64/Makefile:27: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum
arch/arm64/Makefile:57: Detected assembler with broken .inst; disassembly will be unreliable
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      scripts/mod/empty.o
  CC      scripts/mod/devicetable-offsets.s
  HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:111: scripts/dtc/dtc] Error 1
make[1]: *** [scripts/Makefile.build:673: scripts/dtc] Error 2
make[1]: *** Waiting for unfinished jobs....
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/mod/sumversion.o
  CHK     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
make: *** [Makefile:594: scripts] Error 2

Regards

**Comment by fx-09** [comment]
I assume that by closing this issue, it means the problem had been resolved.
