### ISSUE TITLE
Final version Android 10

### ISSUE THREAD

**Issue by ezera23** [halcyon441-png/android_samsung_exynos9610#6]
Hello,

Is the latest final version of the kernel is compatible with Android 10 or only Android R?
The kernel must be build on X86 ?
Regards

**Comment by ezera23** [comment]
bump

**Comment by fx-09** [comment]
Thanks you for participating in my source, @ezera23.
As I have mentioned in my last commit, the version of the kernel is compatible with Android R and build on ARM64, not on x86_64 or x86, those are for old devices only.
Information to you.
-halcyon441
